version: 35
jobs:
- name: pusher all-branch commit
  steps:
  - !PushRepository
    name: force to gh pure-symbols/mabynogion.spells
    remoteUrl: https://github.com/pure-symbols/mabynogion.spells.git
    userName: yhm-amber
    passwordSecret: github.yhm-amber
    force: false
    condition: ALWAYS
  - !PushRepository
    name: force to cb pure-symbols/mabynogion.spells
    remoteUrl: https://codeberg.org/pure-symbols/mabynogion.spells.git
    userName: yhm
    passwordSecret: codeberg.yhm
    force: false
    condition: ALWAYS
  triggers:
  - !BranchUpdateTrigger
    projects: pure.symbols/mabynogion.spells
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: puller all-branch cron.03:20:10
  steps:
  - !PullRepository
    name: force from gh pure-symbols/mabynogion.spells
    remoteUrl: https://github.com/pure-symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALWAYS
  - !PullRepository
    name: force from cb pure-symbols/mabynogion.spells
    remoteUrl: https://codeberg.org/pure-symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: false
    force: false
    condition: ALWAYS
  triggers:
  - !ScheduleTrigger
    cronExpression: 10 20 3 * * ?
    projects: pure.symbols/mabynogion.spells
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
