version: 43
jobs:
- name: pusher all-branch commit
  steps:
  - type: PushRepository
    name: (not force) to gh pure-symbols/mabynogion.spells
    remoteUrl: https://github.com/pure-symbols/mabynogion.spells.git
    userName: yhm-amber
    passwordSecret: github.yhm-amber
    force: false
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: (force) to cb pure-symbols/mabynogion.spells
    remoteUrl: https://codeberg.org/pure-symbols/mabynogion.spells.git
    userName: yhm
    passwordSecret: codeberg.yhm
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: (force) to disrootfj pure.symbols/mabynogion.spells
    remoteUrl: https://git.disroot.org/pure.symbols/mabynogion.spells.git
    userName: ypayhm
    passwordSecret: disroot.ypayhm
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: (force) to framagl pure.symbols/mabynogion.spells
    remoteUrl: https://framagit.org/pure.symbols/mabynogion.spells.git
    userName: ypayhm
    passwordSecret: framagl.ypayhm
    force: true
    condition: ALWAYS
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
    projects: pure.symbols/mabynogion.spells
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: puller all-branch cron.03:20:10
  steps:
  - type: PullRepository
    name: (force) from gh pure-symbols/mabynogion.spells
    remoteUrl: https://github.com/pure-symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: true
    condition: ALWAYS
    optional: false
  - type: PullRepository
    name: (not force) from cb pure-symbols/mabynogion.spells
    remoteUrl: https://codeberg.org/pure-symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  - type: PullRepository
    name: (not force) from disrootfj pure.symbols/mabynogion.spells
    remoteUrl: https://git.disroot.org/pure.symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  - type: PullRepository
    name: (not force) from framagl pure.symbols/mabynogion.spells
    remoteUrl: https://framagit.org/pure.symbols/mabynogion.spells.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 10 20 3 * * ?
    projects: pure.symbols/mabynogion.spells
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
